language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --dev --prefer-source;
  - mysql -e "create database IF NOT EXISTS tocat;" -uroot

script:
  - ./vendor/bin/phpunit --bootstrap=tests/Bootstrap.php
  - ./vendor/bin/phpcs -n --standard=PSR2 ./module/ ./tests/

notifications:
  email: false
  hipchat:
    rooms:
      - secure: "TQDUDVYrJE8a4AqL/ITAeQ7Jo21ZhHXLFjEqukscFFlZlAs/IRqncCTRDSt5zeYvF92yNY9C0KsBTDFU/adYEMq/V41TS5E7mj3T7xYSLX9Vo5N3kmm0RuW1oQhOA78EVOYsHzNSBp6r5na2s7Av0hqdAzFq9oLlT5zgTTqjPBw="
    template:
      - 'BUILD #%{build_number} - <b>%{repository}</b> (<i>%{commit} (%{branch}): <u>%{author}</u></i>): %{message} (See more: <a href="%{build_url}">Details build</a> / <a href="%{compare_url}">Changeset diff<a>)'
    format: html

matrix:
  allow_failures:
    - php: 5.6
